meta_product_name: "Friend Finder"
meta_title: "Friend Finderr - Kickoff new friendships with Friend Finder!"
meta_description: "This social platform offers you the chance to connect to new people in your area and form lasting friendships."
meta_image: "people.svg" # should exist in `app/assets/images/`
